services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wpu\Graphql\:
    resource: '../Classes/*'

  Wpu\Graphql\Auth\Jwt\JwtAuthInterface:
    class: Wpu\Graphql\Auth\Jwt\HmacJwtAuth
    arguments:
      $issuer: 'localhost'
      $lifetime: 86400
      $key: 'my-secret-123'

  Wpu\Graphql\Action\GraphqlAction:
    public: true
    arguments:
      $requestAuthHandler: '@Wpu\Graphql\Handler\JwtRequestAuthHandler'

  Wpu\Graphql\Action\LoginAction:
    public: true
